echo ""
echo "By delivering this file to NVIDIA, you acknowledge"
echo "and agree that personal information may inadvertently be included in"
echo "the output.  Notwithstanding the foregoing, NVIDIA will use the"
echo "output only for the purpose of investigating your reported issue."
echo ""
